[package]
name = "netlink"
version = "0.1.0"
authors = ["rayhaan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
bytes = "1"
byteorder = "1.4.3"
log = "0.4"
hex = "0.4.3"
neli = "0.6.2"