[workspace]
default-members = ["bin/bgp"]
members         = ["bin/*", "crates/*"]
resolver        = "3"

[workspace.package]
authors     = ["Rayhaan Jaufeerally <rayhaan+git@rayhaan.ch>"]
description = "A Border Gateway Protocol implementation"
edition     = "2024"
homepage    = "https://rayhaan.ch"
license     = "Apache-2.0"
name        = "bgp"
repository  = "https://github.com/net-control-plane/bgp"
version     = "0.0.1"

[workspace.dependencies]
# --- Our crates ---
bgp-packet = { path = "crates/packet" }

# --- General ---
bitfield   = "0.19.0"
bytes      = "1.10.1"
eyre       = "0.6.12"
nom        = "8.0.0"
serde      = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
thiserror  = "2.0.12"
tokio      = { version = "1.44.2", features = ["full"] }
>>>>>>> ferrix/master
