[package]
description        = "A Border Gateway Protocol implementation"
edition.workspace  = true
homepage.workspace = true
license.workspace  = true
name               = "bgp"
version.workspace  = true

[dependencies]
eyre.workspace  = true
strum_macros = "0.27.1"
tokio.workspace = true
